name: sem4_fe
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  intl: ^0.18.1
  qr_flutter: ^4.0.0
  mobile_scanner: ^3.5.1
  jwt_decoder: ^2.0.1
  fl_chart: ^0.63.0
  #  camera: ^0.10.5+9
  face_camera: ^0.1.4
  camera: any
  # Thêm package kiểm tra email
  email_validator: ^3.0.0
  geolocator: ^11.0.0
  shared_preferences: ^2.0.15
  # Font biểu tượng iOS
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^7.1.1

  syncfusion_flutter_xlsio: ^22.1.42
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
#flutter_icons:
#  android: true
#  image_path: "assets/images/logo_app.png"
#  # Hoặc chỉ định riêng từng nền tảng
#  min_sdk_android: 21
  assets:
#    - assets/logo_app.png
    - assets/anh.png
    - assets/hr.png
    - assets/avatar.jpg